#!/bin/sh
# /Library/Application\ Support/JAMF/bin/jamfHelper.app/Contents/MacOS/jamfHelper -windowType hud -lockHUD -icon /Applications/Utilities/Adobe\ Flash\ Player\ Install\ Manager.app/Contents/Resources/FlashPlayerInstaller.icns  -timeout 5 -heading "Flash Player" -description "Checking for updates..."
# Set the date & time as a variable 
the_date=`date "+%Y-%m-%d"`
the_time=`date "+%r"`

/Library/Application\ Support/JAMF/bin/jamfHelper.app/Contents/MacOS/jamfHelper -windowType hud -title "$the_time" -icon /Applications/Utilities/Adobe\ Flash\ Player\ Install\ Manager.app/Contents/Resources/FlashPlayerInstaller.icns -heading "Flash Player" -description "Checking for updates..." >&- &


# This script downloads and installs the latest Flash player for compatible Macs

# Determine OS version
osvers=$(sw_vers -productVersion | awk -F. '{print $2}')

# Determine current major version of Adobe Flash for use
# with the fileURL variable

flash_major_version=`/usr/bin/curl --silent https://get.adobe.com/flashplayer/download/?installer=FP_30_Mac_for_Safari_and_Firefox_-_NPAPI&stype=7608&standalone=1 | cut -d , -f 1 | awk -F\" '/update version/{print $NF}'`

# Specify the complete address of the Adobe Flash Player
# disk image
 
fileURL="https://get.adobe.com/flashplayer/download/?installer=FP_30_Mac_for_Safari_and_Firefox_-_NPAPI&stype=7608&standalone=1"

# Specify name of downloaded disk image

flash_dmg="/tmp/flash.dmg"

if [[ ${osvers} -lt 6 ]]; then
  echo "Adobe Flash Player is not available for Mac OS X 10.6.8 or below."
fi

if [[ ${osvers} -ge 6 ]]; then
 
    # Download the latest Adobe Flash Player software disk image

    /usr/bin/curl --output "$flash_dmg" "$fileURL"

    # Specify a /tmp/flashplayer.XXXX mountpoint for the disk image
 
    TMPMOUNT=`/usr/bin/mktemp -d /tmp/flashplayer.XXXX`

    # Mount the latest Flash Player disk image to /tmp/flashplayer.XXXX mountpoint
 
    hdiutil attach "$flash_dmg" -mountpoint "$TMPMOUNT" -nobrowse -noverify -noautoopen

    # Install Adobe Flash Player from the installer package stored inside the disk image

    /usr/sbin/installer -dumplog -verbose -pkg "$(/usr/bin/find $TMPMOUNT -maxdepth 1 \( -iname \*\.pkg -o -iname \*\.mpkg \))" -target "/"

    # Clean-up
 
    # Unmount the Flash Player disk image from /tmp/flashplayer.XXXX
 
    /usr/bin/hdiutil detach "$TMPMOUNT"
 
    # Remove the /tmp/flashplayer.XXXX mountpoint
 
    /bin/rm -rf "$TMPMOUNT"

    # Remove the downloaded disk image

    /bin/rm -rf "$flash_dmg"
fi
# wait

killall jamfHelper
wait 2>/dev/null

/Library/Application\ Support/JAMF/bin/jamfHelper.app/Contents/MacOS/jamfHelper -windowType hud -title "$the_time" -icon /Applications/Utilities/Adobe\ Flash\ Player\ Install\ Manager.app/Contents/Resources/FlashPlayerInstaller.icns  -timeout 5 -heading "Flash Player" -description "Checking for updates... DONE" >&-

exit 0
